### ISSUE TITLE
repo is not linked to synapse (not a proper fork)

### ISSUE THREAD

**Issue by MrRinkana** [beeper/synapse#35]
Albeit a fork of synapse, this repo seems to be deattached and is no longer linked to the upstream repository. This has the following drawbacks:
* There is no link back to the upstream repo
* This repo is not listed as a fork in the upstream repo
* Most importantly differences are **no longer easily compared** with the "commits ahead/behind" menu otherwise offered by github.

Based on the bleeper blog you want to provide a good matrix experience, and thus it does not make sense to deattach the repo as you will want to keep up to date with the synapse main repo.

I'm not sure how (re?)linking a repo as a fork works and since the upstream moved to https://github.com/element-hq/synapse maybe a rebase will be needed.

**Comment by Fizzadar** [comment]
Hi @MrRinkana, we do maintain a fork here for changes we intend to upstream: https://github.com/beeper/synapse-fork

We unforked this repository to simplify our workflows (ie GH doesn’t allow any way to make PRs target the fork not source). The changes here are roughly 25 commits we reapply over upstream whenever we update.

Re: diff we can fix this by keeping our upstream branches about, making compare between version x and x-beeper trivial. I’ll update the readme to make this more clear as well.
